# Lista de exercícios sobre libraria Numpy

<br/>**Disciplina**: Introdução a redes neurais profundas 2018/1
<br/>**Professor**: Jorge Leonid Aching Samatelo

**Aluno**: Humberto da Silva Neto

## Tabela de conteúdos
1. [Indicações](#indicacoes)
1. [Exercícios sobre Numpy](#ExerNumpy)
1. [Exercícios de Programação](#ExerProgramacao)

## Indicações <a name="indicacoes"></a>

### Considerações
* Cada aluno enviará por e-mail a solução dos exercícios propostos, tais soluções devem ser inseridas neste mesmo arquivo. 
* Para saber sobre a libraria `numpy` é necessario ler os slides `NUMPY_2x2.pdf`.
* Para saber cómo trabalhar com arquivos `*.ipynb` é necessario ler os slides `003_JUPYTER_2x2.pdf`.
* Usar o interprete de `python 3.5`.

### Prazo
* Envio das soluções: Domingo 29/04/2018 - (11:59 pm) 

### Procedimento para o envio das soluções
* O arquivo `*.ipynb` com as soluções dos exercícios deve ser enviado ao email <jlasam001@gmail.com> com o assunto: `LISTA_EXERCICIO_NUMPY_2018_1`. 
* O nome do arquivo `*.ipynb` deve iniciar com o rotulo `DL_LISTA_NUMPY` seguido pelas iniciais do nome do aluno que soluciono os exercícios (por exemplo, o aluno Pedro Farias enviara o arquivo `DL_LISTA_NUMPY_PF.ipynb`).

### Dicas execução
* Carregue todos os pacotes que serão necessários no início do arquivo.
* Para executar comandos da shell dentro do notebook, utilize o prefixo `!` antes do comando de shell. (e.g. para listar os arquivos da pasta atual faça `! ls` para UNIX ou `! dir` para Windows.

## Exercícios sobre Numpy <a name="ExerString"></a>

## Exe. 1
Crie uma matriz nxn com valores 1,2,...,n-1 logo abaixo da diagonal.

Exemplo: Considerando n = 4.
```
A = [0 0 0 0 0]
    [1 0 0 0 0]
    [0 2 0 0 0]
    [0 0 3 0 0]
    [0 0 0 4 0]
```

In [1]:
from numpy import zeros

def under_diag(n):
  A = zeros((n+1,n+1))
  for i in range(1,n+1):
    A[i,i-1] = i
    
  return A

print(under_diag(5))

[[0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0.]
 [0. 2. 0. 0. 0. 0.]
 [0. 0. 3. 0. 0. 0.]
 [0. 0. 0. 4. 0. 0.]
 [0. 0. 0. 0. 5. 0.]]


## Exe. 2
Crie uma matriz nxn com 1 na borda e 0 dentro.

Exemplo: Considerando n = 10.
```
Z = [ 1.  1.  1.  1.  1.  1.  1.  1.  1.  1.]
    [ 1.  0.  0.  0.  0.  0.  0.  0.  0.  1.]
    [ 1.  0.  0.  0.  0.  0.  0.  0.  0.  1.]
    [ 1.  0.  0.  0.  0.  0.  0.  0.  0.  1.]
    [ 1.  0.  0.  0.  0.  0.  0.  0.  0.  1.]
    [ 1.  0.  0.  0.  0.  0.  0.  0.  0.  1.]
    [ 1.  0.  0.  0.  0.  0.  0.  0.  0.  1.]
    [ 1.  0.  0.  0.  0.  0.  0.  0.  0.  1.]
    [ 1.  0.  0.  0.  0.  0.  0.  0.  0.  1.]
    [ 1.  1.  1.  1.  1.  1.  1.  1.  1.  1.]
```

In [2]:
from numpy import ones

def border(n):
  A = ones((n,n))
  A[1:-1,1:-1] = 0
  return A
  
print(border(10))

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


## Exe. 3
Crie uma matriz nxn, com n par, e preenchê-lo com um padrão de xadrez.

Exemplo: Considerando n = 8.
```
Z = [0 1 0 1 0 1 0 1]
    [1 0 1 0 1 0 1 0]
    [0 1 0 1 0 1 0 1]
    [1 0 1 0 1 0 1 0]
    [0 1 0 1 0 1 0 1]
    [1 0 1 0 1 0 1 0]
    [0 1 0 1 0 1 0 1]
    [1 0 1 0 1 0 1 0]
```

In [3]:
from numpy import zeros
from numpy import array

def numpy_bin(n):
  if (n%2 != 0):
    return 'Argumento inválido! Tente um numero par.'
  
  else:
    A = zeros((n,n))
    for i in range(A.shape[0]):
      for j in range(A.shape[1]):
        A[i,j] = 1 if (i+j)%2 != 0 else 0     
    
    return A
    
print(numpy_bin(8))

[[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]


## Exe. 4
Criar um vetor de tamanho 10 inicializada com valores entre $<0,1>$.

Exemplo:
```
Z= [0.091 0.181 0.272 0.363 0.454 0.545 0.636 0.727 0.818 0.909]
```

In [4]:
from numpy import linspace

A = linspace(0,1,12)
A = A[1:-1]
print(A)

[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]


## Exe. 5
Dado um array, negar todos os elementos que estão entre 3 e 8.

Exemplo:
```
Zorg =  [ 0  1  2  3  4  5  6  7  8  9 10]
Ztrf =  [ 0  1  2  3 -4 -5 -6 -7 -8  9 10]
```

In [5]:
from numpy import arange

def neg_array(array, min=3, max=8):
  for i in range(array.size):
    array[i] = -array[i] if min <= array[i] <= max else array[i]
    
  return array
  
  
Zorg = arange(0,11)
Ztrf = neg_array(Zorg)
print(Ztrf)

[ 0  1  2 -3 -4 -5 -6 -7 -8  9 10]


## Exe. 6
Extraia a parte inteira de uma array de números aleatórios entre  1.0 e 10.0 usando 5 métodos diferentes.

Exemplo (para um caso):
```
Z  =  [7.497 6.573 9.946 2.645 2.501 8.911 4.301 9.643 4.361 4.128]
Z1 =  [ 7.  6.  9.  2.  2.  8.  4.  9.  4.  4.]
```

In [6]:
from numpy import array, floor, trunc, mod, modf

def method_1(array):
  return array.astype(int)
  
def method_2(array):
  return floor(array)

def method_3(array):
  return trunc(array)
  
def method_4(array): 
  return array - mod(array,1)

def method_5(array):
  return modf(array)[1]

Z = array([7.497, 6.573, 9.946, 2.645, 2.501, 8.911, 4.301, 9.643, 4.361, 4.128])

print(method_1(Z))
print(method_2(Z))
print(method_3(Z))
print(method_4(Z))
print(method_5(Z))

[7 6 9 2 2 8 4 9 4 4]
[7. 6. 9. 2. 2. 8. 4. 9. 4. 4.]
[7. 6. 9. 2. 2. 8. 4. 9. 4. 4.]
[7. 6. 9. 2. 2. 8. 4. 9. 4. 4.]
[7. 6. 9. 2. 2. 8. 4. 9. 4. 4.]


## Exe. 7
Considere dois arrays $A$ e $B$ aleatórios inicializados com valores aleatorios inteiros, verifique se eles são iguais.

Exemplo:
```
A =  [2 2 0 2 1]
B =  [1 0 2 3 3]
False
```

In [7]:
from numpy import array

A =  array([2, 2, 0, 2, 1])
B =  array([1, 0, 2, 3, 3])

print(all(A==B))
print(all(A==A))

False
True


## Exe. 8
Considere uma matriz aleatória de 10x2 que representa coordenadas cartesianas, converta-as em coordenadas polares.

In [8]:
from numpy import array, sqrt, arctan2, vstack

def cart2pol(coordinates): 
  for i in range(coordinates.shape[0]):
    rho = sqrt(coordinates[i,0]**2 + coordinates[i,1]**2)
    phi = arctan2(coordinates[i,1], coordinates[i,0])
    
    if (i==0):
      output = array([rho, phi])
    
    else:
      output = vstack([output, array([rho, phi])])
      
  return output    
  
A =  array([[3, 3, 0, 2, 1, 4, 7, 2, 3, 3], [4, 7, 2, 3, 3, 3, 3, 0, 2, 1]]).T
B = cart2pol(A)

for i in range(A.shape[0]):
  print('Cart2pol: {} ---> {}'.format(A[i],B[i]))

Cart2pol: [3 4] ---> [5.         0.92729522]
Cart2pol: [3 7] ---> [7.61577311 1.16590454]
Cart2pol: [0 2] ---> [2.         1.57079633]
Cart2pol: [2 3] ---> [3.60555128 0.98279372]
Cart2pol: [1 3] ---> [3.16227766 1.24904577]
Cart2pol: [4 3] ---> [5.         0.64350111]
Cart2pol: [7 3] ---> [7.61577311 0.40489179]
Cart2pol: [2 0] ---> [2. 0.]
Cart2pol: [3 2] ---> [3.60555128 0.5880026 ]
Cart2pol: [3 1] ---> [3.16227766 0.32175055]


## Exe. 9
Considere o vetor [1, 2, 3, 4, 5], como construir um novo vetor com 3 zeros consecutivos intercalados entre cada valor.

Exemplo:
```
Zorg =  [1 2 3 4 5]
Z000 =  [ 1.  0.  0.  0.  2.  0.  0.  0.  3.  0.  0.  0.  4.  0.  0.  0.  5.]
```

In [9]:
from numpy import array, zeros, insert

def add_000(array):
  z = zeros(3).astype(int)
  
  for i in range(array.size-1):
    array = insert(array,1+4*i,z)
    
  return array
    
Zorg = array([1, 2, 3, 4, 5])
print(add_000(Zorg))

[1 0 0 0 2 0 0 0 3 0 0 0 4 0 0 0 5]


## Exe. 10
Encontre o valor mais próximo de um dado valor em um array.

Exemplo:
```
Z =  [0.198 0.825 0.057 0.695 0.0333 0.793 0.526 0.547 0.787  0.656]
valor =  0.5
valor proximo em Z = 0.526929001754
```

In [10]:
from numpy import array

def nearest_in(array, value):
  idx = (abs(array-value)).argmin()
  return array[idx]
  
a = array([0.198, 0.825, 0.057, 0.695, 0.0333, 0.793, 0.526, 0.547, 0.787, 0.656])
print(nearest_in(a,0.5))

0.526


## Exercícios de Programação <a name="ExerProgramacao"></a>

## Exe. 1

Como encontrar o valor mais freqüente em um array?

Exemplo:
```
Z = [8 1 8 1 9 6 2 7 0 1 7 1 6 7 9 6 0 2 1 9 8 9 0 6 9 7 1 4 2 8 1 6 4 6 1 3 5 0 1 1 5 5 0 9 4 9 9 1 1 2]
ValMoreFreq = 1
```

In [11]:
from numpy import array, bincount, argmax

Z = array([8, 1, 8, 1, 9, 6, 2, 7, 0, 1, 7, 1, 6, 7, 9, 6, 0, 2, 1, 9, 8, 9, 0, 6, 9,
           7, 1, 4, 2, 8, 1, 6, 4, 6, 1, 3, 5, 0, 1, 1, 5, 5, 0, 9, 4, 9, 9, 1, 1, 2])

ValMoreFreq = argmax(bincount(Z))
print(ValMoreFreq)

1


## Exe. 2

Considere duas matrizes A e B de forma (8,3) e (2,2). Como encontrar as linhas de A que contêm elementos de cada linha de B independentemente da ordem dos elementos em B? 

Exemplo:
```
A = [[2 1 4]
     [3 2 2]
     [3 4 1]
     [3 0 0]
     [4 3 4]
     [0 0 1]
     [2 1 4]
     [0 3 1]]
B = [[1 4]
     [2 4]]
rows = [0 1 2 4 6]
```

In [12]:
from numpy import array, isin

def b_in_A(A, B):
  rows = []
  I = isin(A, B, assume_unique=True)
  
  for i in range(A.shape[0]):
    rows.append(i) if sum(I[i])>1 else None
    
  return rows

A = array([[2, 1, 4],
           [3, 2, 2],
           [3, 4, 1],
           [3, 0, 0],
           [4, 3, 4],
           [0, 0, 1],
           [2, 1, 4],
           [0, 3, 1]])

B = array([[1, 4],
           [2, 4]])

lst = b_in_A(A,B)
print(lst)

[0, 1, 2, 4, 6]


## Exe. 3
Dado um array bidimensional, como extrair linhas unicas?

Exemplo:
```
Z = [[0 0 1]
     [1 0 0]
     [1 1 0]
     [1 1 1]
     [0 1 1]
     [1 1 0]]
Zu = [[0 0 1]
      [0 1 1]
      [1 0 0]
      [1 1 0]
      [1 1 1]]
```

In [13]:
from numpy import array, unique

Z = array([[0, 0, 1],
           [1, 0, 0],
           [1, 1, 0],
           [1, 1, 1],
           [0, 1, 1],
           [1, 1, 0]])

Zu = unique(Z, axis=0)

print('Z:\n',Z,'\n')
print('Zu:\n',Zu)

Z:
 [[0 0 1]
 [1 0 0]
 [1 1 0]
 [1 1 1]
 [0 1 1]
 [1 1 0]] 

Zu:
 [[0 0 1]
 [0 1 1]
 [1 0 0]
 [1 1 0]
 [1 1 1]]


## Exe. 4
Converter um vetor de inteiros em uma matriz que seja sua representação binária.

Exemplo:
```
I = [0 1 2 3 15 16 32 64 128]
B = [[0 0 0 0 0 0 0 0]
     [0 0 0 0 0 0 0 1]
     [0 0 0 0 0 0 1 0]
     [0 0 0 0 0 0 1 1]
     [0 0 0 0 1 1 1 1]
     [0 0 0 1 0 0 0 0]
     [0 0 1 0 0 0 0 0]
     [0 1 0 0 0 0 0 0]
     [1 0 0 0 0 0 0 0]]
```

In [14]:
from numpy import array, amax, vstack, binary_repr

def arr2bin(x):
  x_max = amax(x)
  width = int(x_max).bit_length()
  
  for i in range(x.size):
    if (i == 0):
      output = array(list(binary_repr(x[i], width=width)))
      
    else:
      output = vstack([output, array(list(binary_repr(x[i], width=width)))])
  
  return output.astype(int)

I = array([0, 1, 2, 3, 15, 16, 32, 64, 128])

I_bin = arr2bin(I)
print(I_bin)

[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 1 1]
 [0 0 0 0 1 1 1 1]
 [0 0 0 1 0 0 0 0]
 [0 0 1 0 0 0 0 0]
 [0 1 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0]]


## Exe. 5
Considerando uma matriz 10x3, extraia linhas com valores desiguais (por exemplo, [2,2,3])

Exemplo:
```
Z = [[2 2 0]
     [1 1 3]
     [4 3 3]
     [1 0 1]
     [2 2 2]
     [2 3 3]
     [1 1 0]
     [0 2 0]
     [4 4 0]
     [4 2 3]]
Zd = [[2 2 0]
      [1 1 3]
      [4 3 3]
      [1 0 1]
      [2 3 3]
      [1 1 0]
      [0 2 0]
      [4 4 0]
      [4 2 3]]
```

In [15]:
from numpy import array, unique, vstack

def only_diff(matrix):
  flag = 0
  
  for i in matrix:
    if (unique(i).size > 1):
      if (flag == 0):
        output = i
        flag +=1
      
      else:
        output = vstack([output, i])
      
  return output
    
Z = array([[2, 2, 0],
     [1, 1, 3],
     [4, 3, 3],
     [1, 0, 1],
     [2, 2, 2],
     [2, 3, 3],
     [1, 1, 0],
     [0, 2, 0],
     [4, 4, 0],
     [4, 2, 3]])

print(only_diff(Z))

[[2 2 0]
 [1 1 3]
 [4 3 3]
 [1 0 1]
 [2 3 3]
 [1 1 0]
 [0 2 0]
 [4 4 0]
 [4 2 3]]
